export enum CartActionTypes {
  TOGGLE_CART_HIDDEN = 'TOGGLE_CART_HIDDEN',
  ADD_PRODUCT = 'ADD_PRODUCT',
  DELETE_PRODUCT = 'DELETE_PRODUCT',
  REDUCE_QUANTITY = 'REDUCE_QUANTITY',
  REMOVE_LAST_PRODUCT = 'REMOVE_LAST_PRODUCT'
}

export default CartActionTypes; 